# Generated by Django 4.2.7 on 2023-11-15 13:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import shops.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=30, verbose_name='Название города')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=50, verbose_name='Название улицы')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.city', verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=30, verbose_name='Название магазина')),
                ('house_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='Номер дома')),
                ('time_open', models.TimeField(validators=[shops.validators.validate_time], verbose_name='Время открытия')),
                ('time_close', models.TimeField(validators=[shops.validators.validate_time], verbose_name='Время закрытия')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.street', verbose_name='Улица')),
            ],
        ),
    ]
